apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "tmc.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "tmc.name" . }}
    chart: {{ template "tmc.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "tmc.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "tmc.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: ACCEPT_EULA
          value: "{{ .Values.template.spec.env.ACCEPT_EULA }}"
        - name: TMS_DEFAULTURL
          value: "{{ .Values.template.spec.env.TMS_DEFAULTURL }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        volumeMounts:
        - name: {{ .Values.spec.template.spec.containers.volumeMounts.name }}
          mountPath: {{ .Values.spec.template.spec.containers.volumeMounts.mountPath }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets.name }}
      volumes:
        - name: {{ .Values.spec.template.spec.volumes.name }}
          hostPath:
            path: {{ .Values.spec.template.spec.volumes.hostPath.path }}
