# Default values for TMC.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: tmc
service:
  type: NodePort
  port: 9480
replicaCount: 1
namespace: tmc
imagePullSecrets:
  name: regcred
image:
  repository: store/softwareag/tmc
  tag: 10.3
  pullPolicy: Always
#default for TMC connection url and license acceptance
template:
  spec:
    env:
      ACCEPT_EULA: "Y"
      TMS_DEFAULTURL: "terracotta://localhost:9410"
#define volumes mounts
spec:
  template:
    spec:
      containers:
        volumeMounts:
            name: tmcdata
            mountPath: /data/tmc/
      volumes:
         name: tmcdata
         hostPath: 
          path: /home/docker/tmcdata